### PR TITLE
Fix the syntax of a few disabled tests.

### PR DESCRIPTION
**Pull request by GUIpsp**
They are disabled, but they are still interesting tests. This commit makes them syntatically correct

### CODE REVIEW

**Comment by tgehr** [comment]
Well, technically nothing is broken, but I agree that your formatting is more consistent. Thanks!

**Comment by GUIpsp** [comment]
Not sure about your tool - but my parser choked on these. The syntax isn't fully described, but makes sense it should choke: expressions are not statements and vice versa.

Also some other weird things I found in other examples:

* Block comments: /++/ or /**/?
* Anonymous functions: (){}, ()=>{} or ()⇒{}?

**Comment by tgehr** [comment]
Well, there are multiple things going on here:
-  In PSI, `;` is a separator of statements, not a terminator, so it is optional for the last statement.
- The parser does not really make a distinction between expressions, statements and types, this is sorted out during type checking. I guess it would be simple enough to disallow semicolons in a noisy-style if expression that occurs in an expression context.

Regarding your questions:
- Block comments: `/++/` are nesting block comments, while `/**/` are C/Java-style comments that don't nest. I guess an alternative design would be to allow `/**/` to nest like in e.g. Scala, but the lexer was originally a lexer for D, and the comment syntax was kind of just carried over this way. I think `/++/` is more convenient to type anyway.
- Anonymous functions are `(){}`. `()=>exp` and `()⇒exp` are short-hand forms of `(){ return exp; }`. `()=>()` and `()⇒{}` are syntax errors.

**Comment by GUIpsp** [comment]
@tgehr Thanks for the clarification, this is quite helpful. Would it be ok if I submitted another PR in the spirit of this one for other inconsistencies I found?

**Comment by tgehr** [comment]
@GUIpsp Sure! Feel free to open further pull requests, I will pull them if I consider them an improvement.

**Pull request merged**
